"""Liverpool Airport (LPL) destinations — May 2026."""

DESTINATIONS = {
    "LPL": {
        "name": "Liverpool",
        "routes": {
            "ACE": "Lanzarote",
            "AGA": "Agadir",
            "AGP": "Malaga",
            "ALC": "Alicante",
            "AMS": "Amsterdam",
            "AYT": "Antalya",
            "BCN": "Barcelona",
            "BER": "Berlin",
            "BFS": "Belfast Intl",
            "BGO": "Bergen",
            "BHD": "Belfast City",
            "BJV": "Bodrum",
            "BOJ": "Bourgas",
            "BUD": "Budapest",
            "CDG": "Paris CDG",
            "CFU": "Corfu",
            "DLM": "Dalaman",
            "DUB": "Dublin",
            "EGC": "Bergerac",
            "FAO": "Faro",
            "FCO": "Rome",
            "FNC": "Funchal",
            "FUE": "Fuerteventura",
            "GDN": "Gdansk",
            "GVA": "Geneva",
            "HER": "Heraklion",
            "IAS": "Iasi",
            "IBZ": "Ibiza",
            "IOM": "Isle of Man",
            "JER": "Jersey",
            "KEF": "Reykjavik",
            "KGS": "Kos",
            "KRK": "Krakow",
            "KSC": "Kosice",
            "KUN": "Kaunas",
            "LCA": "Larnaca",
            "LDY": "Derry",
            "LEI": "Almeria",
            "LIS": "Lisbon",
            "LPA": "Gran Canaria",
            "MAD": "Madrid",
            "MAH": "Menorca",
            "MLA": "Malta",
            "MXP": "Milan",
            "NAP": "Naples",
            "NBE": "Enfidha",
            "NCE": "Nice",
            "NOC": "Knock",
            "OPO": "Porto",
            "ORK": "Cork",
            "OSL": "Oslo",
            "OTP": "Bucharest",
            "PFO": "Paphos",
            "PMI": "Palma",
            "POZ": "Poznan",
            "PRG": "Prague",
            "RAK": "Marrakesh",
            "REU": "Reus",
            "RHO": "Rhodes",
            "RVN": "Rovaniemi",
            "SNN": "Shannon",
            "SOF": "Sofia",
            "SPU": "Split",
            "SZG": "Salzburg",
            "SZZ": "Szczecin",
            "TFS": "Tenerife",
            "TIA": "Tirana",
            "TRN": "Turin",
            "VIE": "Vienna",
            "WAW": "Warsaw",
            "WRO": "Wroclaw",
            "ZAD": "Zadar",
            "ZTH": "Zante",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
